// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA32-xzZcT61qTLvT9xi4isbCanf-Qoi3Y',
    appId: '1:871625933939:web:355377a60367c1dae19606',
    messagingSenderId: '871625933939',
    projectId: 'flutter-login-4e444',
    authDomain: 'flutter-login-4e444.firebaseapp.com',
    storageBucket: 'flutter-login-4e444.appspot.com',
    measurementId: 'G-Q0BTEM228V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMs6bzk2_w80elrf-yJftfPfIE61SjKfU',
    appId: '1:871625933939:android:0d46e8c2ed6e1bcbe19606',
    messagingSenderId: '871625933939',
    projectId: 'flutter-login-4e444',
    storageBucket: 'flutter-login-4e444.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuvXFPhussL0F-hUdtKcj1b9pp9Eax57M',
    appId: '1:871625933939:ios:74821d9eda400c30e19606',
    messagingSenderId: '871625933939',
    projectId: 'flutter-login-4e444',
    storageBucket: 'flutter-login-4e444.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
